trigger: none

pr: none

pool:
  name: 'Vijay'

variables:
  - group: 'Dev'

stages:
- stage: Dev
  displayName: 'Deploy to Dev'
  jobs:
  - job: Deploy
    displayName: 'Deploy to Dev Environment'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: 'b16c1ef6-dfcd-4618-8e81-dc8ab13dbf2f'
        definition: '2'
        buildVersionToDownload: 'latest'
        artifactName: 'Artifacts_Apps.Data.Processor'
        targetPath: '$(System.ArtifactsDirectory)'

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'ARM Template deployment: Resource Group scope'
      inputs:
        azureResourceManagerConnection: Vijay
        subscriptionId: '22969fb4-b739-47d2-b862-40bbf4e40026'
        resourceGroupName: 'terraform-poc'
        location: 'West Europe'
        csmFile: '$(System.DefaultWorkingDirectory)/Artifacts_Apps.Data.Processor/drop/AppservicePlan.bicep'
        overrideParameters: '-appServicePlanName Terraform-POC'

#- stage: QA
#  displayName: 'Deploy to QA'
#  jobs:
#  - job: Deploy
#    displayName: 'Deploy to QA Environment'
#    dependsOn: BuildPipeline  # Reference the build alias
#    steps:
#    - task: DownloadPipelineArtifact@2
#      inputs:
#        artifactName: 'YourArtifactName'
#        downloadPath: $(System.ArtifactsDirectory)
#        downloadType: 'single'
#        itemPattern: '**'
#        artifactAlias: 'drop'

#- stage: Prod
#  displayName: 'Deploy to Production'
#  jobs:
#  - deployment: Deploy
#    displayName: 'Deploy to Production Environment'
#    environment: 'Production'
#    dependsOn: DeployQA
#    strategy:
#      runOnce:
#        deploy:
#          steps:
#          - task: DownloadPipelineArtifact@2
#            inputs:
#              artifactName: 'YourArtifactName'
#              downloadPath: $(System.ArtifactsDirectory)
#              downloadType: 'single'
#              itemPattern: '**'
#              artifactAlias: 'drop'
#    # Add manual approval for the Production environment
#    condition: succeeded()

resources:
  pipelines:
  - pipeline: Artifacts_Apps.Data.Processor  # Build alias to reference the specific build pipeline
    source: Artifacts\Artifacts_Apps.Data.Processor  # Name of the build pipeline defined in build-pipeline.yml
    trigger:
      branches:
        exclude:
          - '*'
